### PR TITLE
Change from RawGit to jsDelivr

### LINKED ISSUE #223: Demo site doesn't work
Hi there

Thank you all for the great work done here.

I've just found the cryptoicoins.co is empty and doesn't display any coins examples

screen shot 2018-09-24 at 15 09 11

### PR DESCRIPTION
**Pull request by jenbuzz**
Current live site is not working. A 'Access-Control-Allow-Origin' error is holding it back. Changing the rawgit urls to use their cdn seems to fix the issue.

Fixes atomiclabs/cryptocurrency-icons#223

### CODE REVIEW

File: main.js [hunk 1]
```diff
@@ -1,8 +1,8 @@
 // ------------------------------
 // Settings
 // ------------------------------
-const iconsBaseUrl = 'https://rawgit.com/atomiclabs/cryptocurrency-icons/master';
-const dataJson = 'https://rawgit.com/atomiclabs/cryptocurrency-icons/master/manifest.json';
+const iconsBaseUrl = 'https://cdn.rawgit.com/atomiclabs/cryptocurrency-icons/master';
+const dataJson = 'https://cdn.rawgit.com/atomiclabs/cryptocurrency-icons/master/manifest.json';
```
Comment (sindresorhus) [inline main.js]: We can't use the `master` branch if we use the CDN as it will then never update when we add new coins. We need to use a specific commit, but we also don't want to have to manually update the commit SHA every time we add a new icon, so I think the solution would be to fetch the latest commit SHA from the `cryptocurrency-icons` repo and use it here in the URL instead of the `master` branch.

Comment (jenbuzz) [reply main.js]: I replaced RawGit with jsDelivr since RawGit is shutting down. Also using the latest commit SHA to fetch them.

**Comment by sindresorhus** [comment]
Thank you so much for fixing this, @jenbuzz 🙌
